version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ayushikansal168/node-app:latest
    ports:
      - "3000:3333"
    container_name: node-app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
