name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_HUB_REPO_NAME }}:latest

  deploy:
    name: Deploy to Server via SSM
    runs-on: ubuntu-latest
    needs: build-and-push

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy Application with AWS SSM
      run: |
        INSTANCE_ID=${{ vars.INSTANCE_ID }}
        COMMAND=${{ vars.COMMAND }}

        # Send the command to the instance
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=$INSTANCE_ID" \
          --parameters "commands=$COMMAND" \
          --comment "Deploy updated Docker Compose application" \
          --region ${{ secrets.AWS_REGION }} \
          --query 'Command.CommandId' \
          --output text

          echo "command_id=$command_id" >> $GITHUB_ENV
