name: Docker Compose Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        # Navigate to the deployment directory
        mkdir -p ~/docker-app
        cd ~/docker-app

        # Stop and remove the current containers
        docker-compose down

        # Clean up old files
        rm -rf *

        # Exit from SSH session
        EOF

        # Upload new Docker Compose files to the EC2 instance
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/docker-app/

        # Run Docker Compose to deploy the updated application
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd ~/docker-app

        # Pull updated images and restart containers
        docker-compose pull
        docker-compose up -d
        EOF
